name: Build and Run JUnit Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Ensure gradlew is executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run JUnit Tests with Gradle
        run: ./gradlew test

      - name: Generate Test Summary
        if: always()
        run: |
          TOTAL=$(grep -oP '(?<=tests=")[0-9]+' build/test-results/test/*.xml | awk '{s+=$1} END {print s+0}')
          FAILED=$(grep -oP '(?<=failures=")[0-9]+' build/test-results/test/*.xml | awk '{s+=$1} END {print s+0}')
          ERRORS=$(grep -oP '(?<=errors=")[0-9]+' build/test-results/test/*.xml | awk '{s+=$1} END {print s+0}')
          SKIPPED=$(grep -oP '(?<=skipped=")[0-9]+' build/test-results/test/*.xml | awk '{s+=$1} END {print s+0}')
          
          PASSED=$((TOTAL - FAILED - ERRORS - SKIPPED))
          
          echo "Tests Passed: [$PASSED/$TOTAL] | Failed: $FAILED | Errors: $ERRORS | Skipped: $SKIPPED"

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: build/test-results
